name: flutter_application_1
description: "APK"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: ^0.20.2
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.1
  image_picker: ^1.1.2
  pinput: ^4.0.0
  google_fonts: ^6.2.1
  dotted_border: ^2.1.0
  file_picker: ^8.0.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  video_player: ^2.8.1
  share_plus: ^9.0.0
  cross_file: ^0.3.4
  path_provider: ^2.1.3
  gal: ^2.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/splash_bg.png
    - assets/map_bg.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/flag.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/flag.png"
    background_color: "#ffffff"
    theme_color: "#0D47A1"
  windows:
    generate: true
    image_path: "assets/flag.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/flag.png"
