name: flutter_application_1
description: "APK"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: ^0.20.2
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/splash_bg.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/flag.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/flag.png"
    background_color: "#ffffff"
    theme_color: "#0D47A1"
  windows:
    generate: true
    image_path: "assets/flag.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/flag.png"
